- kong/Dockerfile
- kong/Jenkinsfile
- kong/README.md
- kong/docker-entrypoint.sh
> init new kong base build image

- golang/Jenkinsfile
> add new property to setup webhook

- golang/Jenkinsfile
> script block did not work. reverting

- lftools/Dockerfile
- lftools/Jenkinsfile
- lftools/fedora-infra-sigul.repo
Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>
> Add lftools base image

- kong/Dockerfile
- kong/Jenkinsfile
> Optimize the kong build by pre-caching layers

- gcc/Jenkinsfile
- golang/Jenkinsfile
- lftools/Jenkinsfile
> update port to 10004

- gcc/Jenkinsfile
- golang/Jenkinsfile
> create nested stage with build and push

- gcc/Jenkinsfile
> fix docker push failures for gcc build

- gcc/Jenkinsfile
- golang/Jenkinsfile
- kong/Jenkinsfile
- lftools/Jenkinsfile
Signed-off-by: Tyler Powers <tyler.m.powers@intel.com>
> add check for file change to build image only when needed

- gcc/Jenkinsfile
- golang/Jenkinsfile
- kong/Jenkinsfile
- lftools/Jenkinsfile
> add println to debug pipeline issues

- golang/Dockerfile
- kong/Dockerfile
> fix copyright year

- kong/Jenkinsfile
> Fix image tag and push steps

- kong-arm-parent/Dockerfile
- kong-arm-parent/Jenkinsfile
> Initialize parent docker image for kong base

- kong-arm-parent/Jenkinsfile
> update debug message

- kong/Dockerfile
> copy pre-built layers from nexus

- klar/Dockerfile
- klar/Jenkinsfile
> initialize new klar docker image

- golang-1.12/.golangci.yml
- golang-1.12/Dockerfile
- golang-1.12/Jenkinsfile
- golang-1.12/linter-settings.json
Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>
> Add golang-1.12 base image

- golang-1.12/Dockerfile
- golang/Dockerfile
Signed-off-by: Tyler Powers <tyler.m.powers@intel.com>
> Add bash to go base for codecov

- README.md
- edgex-docs/Dockerfile
- edgex-docs/Jenkinsfile
> Initial commit of base edgex-docs builder image

- edgex-docs/Jenkinsfile
> add timestamps option to build edgex-docs build

- newman/Dockerfile
- newman/Jenkinsfile
Add newman docker image
Signed-off-by: Cherry Wang <cherry@iotechsys.com>
fix #41
> initialize newman docker image

- edgex-docs/Dockerfile
> remove files /usr/share/docs directory

- jmeter/Dockerfile
- jmeter/Jenkinsfile
- jmeter/entrypoint.sh
Add JMeter docker image for performance test
Signed-off-by: Cherry Wang <cherry@iotechsys.com>
fix #37
> initialize jmeter docker image

- compose/README.md
- robotframework/Dockerfile
- robotframework/Jenkinsfile
- robotframework/README.md
- robotframework/robot-entrypoint.sh
Add Dockerfile and readme for building the docker image.
> Add robotframework, compose folder to build docker image

- golang/Jenkinsfile
> add Clair stage to scan pushed images.

- lftools/Dockerfile
- lftools/Jenkinsfile
> add xmlstartlet dependency

- lftools/Dockerfile
- lftools/Jenkinsfile
> clean yum cache and install pip with no cache

- lftools/Dockerfile
- lftools/Jenkinsfile
> fix docker push stage

- lftools/Dockerfile.logs-publish
> add bash to install

- edgex-docs/Jenkinsfile
Add new parallel stage for ARM based image.
> add ARM64 support

- jq/Dockerfile
- jq/Jenkinsfile
Signed-off-by: Vishwas SP <vishwasx.s.premachandra@intel.com>
> Initial dockerfile for jq

- README.md
> update README with missing links

- jq/Jenkinsfile
> update didChange regex

- jq/Dockerfile
Signed-off-by: Vishwas SP <vishwasx.s.premachandra@intel.com>
> jq support for both x86 and ARM

- jq/Dockerfile
Signed-off-by: Vishwas SP <vishwasx.s.premachandra@intel.com>
> Fix for jq dockerfile

- jq/Jenkinsfile
Signed-off-by: Vishwas SP <vishwasx.s.premachandra@intel.com>
> JQ amd64 and arm64 support added

- snyk/Dockerfile
- snyk/Jenkinsfile
Signed-off-by: Ernesto Ojeda <ernesto.ojead@intel.com>
> add new Snyk image for Go/Docker scanning

- snyk/Jenkinsfile
Signed-off-by: Ernesto Ojeda <ernesto.ojead@intel.com>
> fix missing clair scan image tag

- snyk/Dockerfile
Signed-off-by: Ernesto Ojeda <ernesto.ojead@intel.com>
> add docker binary from docker:latest

- kong-arm-parent/Dockerfile
- kong/Dockerfile
> fix broken pcre ftp download link

- kong/Dockerfile
- kong/docker-entrypoint.sh
> update Dockerfile with changes needed to work with ARM64

- newman/Jenkinsfile
Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>
> Rename newman image in Nexus 3

- Jenkinsfile
> add releaseBranchOverride parameter

- Jenkinsfile
> add new option to allow custom release branch override

- README.md
Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>
> Add golang 1.13 to README

- README.md
Signed-off-by: Emilio Reyes <emilio.reyes@intel.com>
> Add egp-unit-test link to readme

- Jenkinsfile.sandbox
> add sandbox Jenkinsfile

- Jenkinsfile
> add missing releaseBranchOverride

- entrypoint.sh
> remove stray EOF

- Dockerfile
> update to match edgex-global-pipelines ARCH

- Dockerfile
- Dockerfile.logs-publish
- Jenkinsfile
Signed-off-by: James Gregg <james.r.gregg@intel.com>
https://github.com/edgexfoundry/ci-build-images/issues/116
Test Links :
> update lftools to latest v0.31.0

- Dockerfile
Signed-off-by: James Gregg <james.r.gregg@intel.com>
Test Links :
the build breaks for lftools sign git-tag when testing with sample-service.  Ernesto suggested to update to python3 to see if it addresses the error observed in the latest build.
> update lftools to use python3

- Dockerfile
> update alternatives to make python3 default

- Dockerfile
> add fix for urlgrabber python script

- Dockerfile
> add env vars to fix encoding errors

- Dockerfile
- Dockerfile.logs-publish
- Jenkinsfile
> update to version 0.31.1

- Dockerfile
> fix gradle version

- entrypoint.sh
> add apt-get update before snapcraft commands

- .github/pull_request_template.md
Signed-off-by: James Gregg <james.r.gregg@intel.com>
Update PR template as per decision in Architect's meeting 06/15/2020 to add question regarding new dependencies (e.g. imports / modules)
Test Links :
> docs: update pr template to add dependencies question

- Dockerfile
Signed-off-by: Cherry Wang <cherry@iotechsys.com>
fix #134 
Test Links :
Lost "docker" cause the blackbox got failure.
> Add docker to compose image

- Dockerfile
> add missing expect package

- Jenkinsfile
> remove dockerPushLatest

- Dockerfile
> build: update to latest gradle 6.5

- Dockerfile
> chore: update to Go 1.15.2

- Dockerfile.logs-publish
> feat: add components for other lf scripts

- Dockerfile.logs-publish
- lf-env.sh
> bug: add missing files for log publish

- Dockerfile
- Jenkinsfile
> feat: upgrade to v1.419.1

- Dockerfile
> feat: update go version and add expect package

- Dockerfile
> feat: add snyk-to-html utility to generate html report

- Dockerfile
- Jenkinsfile
> Update golang to latest 1.15.5-alpine3.12
